export interface GiftCode {
  code: string;
  date: string; // ISO
  note?: string;
  active?: boolean;
}

// Auto-generated by update_data.py from the official Discord #giftcode channel.
// Newest codes first; active = published within the last 45 days.
export const giftCodes: GiftCode[] = [
  { code: 'LADOG26', date: '2026-08-27', active: true },
  { code: 'LAQIXI26', date: '2026-08-19', active: true },
  { code: 'LA26ALLY', date: '2026-07-31', active: true },
  { code: 'LA25W8CM', date: '2026-07-30', active: true },
  { code: '26CHOCO', date: '2026-07-07', active: false },
  { code: 'LA20WBZ9', date: '2026-06-24', active: false },
  { code: 'LADAD26', date: '2026-06-22', active: false },
  { code: 'LA26PLAY', date: '2026-06-01', active: false },
  { code: 'LA26LOVE', date: '2026-05-11', active: false },
  { code: 'LA15WPN4D', date: '2026-05-11', active: false },
  { code: 'LABOR26', date: '2026-05-01', active: false },
  { code: 'LAEGG26', date: '2026-04-05', active: false },
  { code: 'LA26FOOL', date: '2026-04-01', active: false },
  { code: 'LA1OW9F7X', date: '2026-03-30', active: false },
  { code: 'LAPGPOFF', date: '2026-03-03', active: false },
  { code: 'LAVD26', date: '2026-02-14', active: false },
  { code: 'LANY2026', date: '2026-01-01', active: false },
  { code: 'LAXMAS25', date: '2025-12-25', note: 'Merry Christmas', active: false },
  { code: 'LADCEX1223', date: '2025-12-23', note: 'Discord  Exclusive Rewards', active: false },
];

export const REDEEM_URL = 'https://gevents.globallap.com/gamecode/index.html?gameId=440';
