export interface PatchNote {
  date: string; // ISO date of the announcement
  title: string;
  highlights: string[];
  ru?: {
    title: string;
    highlights: string[];
  };
}

// Auto-generated by update_data.py from the official Discord #patch-notes channel.
// Localized versions added for international community.
export const patchNotes: PatchNote[] = [
  {
    date: '2026-09-02',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Added a toggle button for Official appointment notification banner. You may see this in Settings.',
      'Optimized the search field for Kingdom Commendation.',
      'Optimized the privilege indicators for purchased Alliance Golden Caravan.',
      'Fixed an issue where the Plunder range displayed for Caravan was incorrect under certain conditions.',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Добавлен переключатель баннера уведомлений о назначении на официальную должность в Настройках.',
        'Оптимизировано поле поиска для королевских наград.',
        'Оптимизированы индикаторы привилегий для приобретенного Золотого каравана альянса.',
        'Исправлена ошибка, из-за которой радиус разграбления каравана при определенных условиях отображался некорректно.',
      ],
    },
  },
  {
    date: '2026-08-27',
    title: 'Pandemic Experience update',
    highlights: [
      'Difficulties 10 and 11 will be added to Pandemic Experience starting September 2.',
      'Added an option to allow or block private messages from other players.',
      'Added a Sanctuary Level requirement for other players to initiate private chats.',
      'Covert Ops Force will now display the range of Kingdoms available for plundering.',
    ],
    ru: {
      title: 'Обновление «Опыт пандемии»',
      highlights: [
        'Сложности 10 и 11 добавлены в «Опыт пандемии» со 2 сентября.',
        'Добавлена опция разрешения или блокировки личных сообщений от других игроков.',
        'Добавлено требование к уровню Святилища для отправки личных сообщений.',
        'Отряд спецопераций теперь отображает радиус Королевств, доступных для разграбления.',
      ],
    },
  },
  {
    date: '2026-08-20',
    title: 'Raven Epigraphs update',
    highlights: [
      'Raven Epigraphs can now be upgraded to 6 Stars.',
      'After an Exclusive Weapon reaches 10 Stars, the Smelt feature will unlock, allowing you to further enhance its attributes.',
      'Optimized the display of march routes on the map.',
      'Optimized the display of purchased packs on the Blades Out event screen.',
    ],
    ru: {
      title: 'Обновление Эпиграфов Ворона',
      highlights: [
        'Эпиграфы Ворона теперь можно улучшать до 6 звезд.',
        'При достижении эксклюзивным оружием 10 звезд открывается функция «Переплавка» для дальнейшего усиления атрибутов.',
        'Оптимизировано отображение маршрутов маршей на глобальной карте.',
        'Оптимизировано отображение приобретенных наборов в событии «Клинки наголо».',
      ],
    },
  },
  {
    date: '2026-08-13',
    title: 'Era of Revival rollout',
    highlights: [
      'Era Shop now features [Castle of Revival] Skin.',
      'Expedition League event duration adjusted: 56 days → 55 days.',
      'Era Settlement Reward configuration optimized: [Mythic Era Commendation] chest random reward distribution refined.',
      'Fixed unnecessary bubble display above alliance buildings during garrison.',
    ],
    ru: {
      title: 'Запуск «Эры возрождения»',
      highlights: [
        'В Магазине Эры появился облик замка [Крепость возрождения].',
        'Длительность события «Лига экспедиций» скорректирована: 56 дней → 55 дней.',
        'Оптимизированы финальные награды Эры: уточнены шансы сундука [Мифическая награда Эры].',
        'Исправлено лишнее отображение всплывающего облачка над зданиями альянса во время гарнизона.',
      ],
    },
  },
  {
    date: '2026-08-05',
    title: 'Alliance League update',
    highlights: [
      'Optimized icon display in the top-right corner of the main interface.',
      'Optimized Relocation: allowing relocation onto Covert Operation Quests, and displaced quests will respawn.',
      'Optimized Alliance Trade Caravan with added filtering options during member selection and improved VIP Passenger Wagon Reward selection interaction.',
      'Optimized Alliance League Ranking interface to display the corresponding Kingdom for each Alliance; tap the Flag to view Alliance details.',
    ],
    ru: {
      title: 'Обновление Лиги Альянсов',
      highlights: [
        'Оптимизировано отображение иконок в правом верхнем углу главного экрана.',
        'Оптимизировано перемещение базы: разрешено перемещение на точки заданий Спецопераций (смещенные задания возрождаются рядом).',
        'Оптимизирован Торговый караван альянса: добавлены фильтры участников и улучшен интерфейс выбора наград VIP-вагона.',
        'В рейтинге Лиги Альянсов теперь отображается Королевство каждого альянса; нажатие на флаг открывает профиль.',
      ],
    },
  },
  {
    date: '2026-07-30',
    title: 'Thief Hunt & Alliance optimizations',
    highlights: [
      'Alliance Battle Log: View attack records from Alliance members.',
      'Falcon Tower One-Tap Reward Claim unlocks at Lv.8.',
      'Event Schedule: Major Events requiring reservation or scheduled activation (Hunt Battle, Cheese Trap, etc.) are now displayed in a unified Event Schedule.',
      'Raven interface now features separate buttons for Skin and Upgrade Preview.',
    ],
    ru: {
      title: 'Охота на воров и улучшения альянса',
      highlights: [
        'Журнал битв альянса: просмотр записей атак участников альянса.',
        'Сбор наград Башни сокола в один клик открывается на 8 уровне.',
        'Расписание событий: крупные события с записью (Охота, Ловушка для сыра и др.) объединены в единый календарь.',
        'В интерфейсе Ворона добавлены отдельные кнопки для обликов и предпросмотра улучшений.',
      ],
    },
  },
  {
    date: '2026-07-08',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Specialty Tech unlocks when Research Lab reaches Lv.30 and Elite Troop Tech reaches 80%.',
      'New Alliance Event: Undead Siege (available 2 weeks after server launch).',
      'Research Lab now displays recommended Tech for combat.',
      'Raven Gear interface will display research Progress for Lv.8 and above equipment.',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Специальные технологии открываются при Институте 30 уровня и исследовании Элитных войск на 80%.',
        'Новое событие альянса: «Осада нежити» (доступно через 2 недели после старта сервера).',
        'В Институте теперь отображаются рекомендуемые боевые технологии.',
        'В интерфейсе снаряжения Ворона отображается прогресс исследований экипировки 8+ уровня.',
      ],
    },
  },
  {
    date: '2026-07-01',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'World Map: Sanctuary shields and Burn status are shown when zoom out.',
      'Hero Name: Brian will be renamed to Ulfrid.',
      'Cursed Land: Placement of new Cheese Traps will no longer be permitted in Cursed Land after this update.',
      'Demon King Blight Achievement interface: Damage data will display more clearly after this update.',
    ],
    ru: {
      title: 'Плановые техработы и переименование героев',
      highlights: [
        'Карта мира: щиты городов и статус горения теперь видны при отдалении камеры.',
        'Имя героя: Брайан переименован в Ульфрида.',
        'Проклятые земли: размещение новых Ловушек для сыра в Проклятых землях запрещено.',
        'Достижения «Чумной Король Демонов»: данные об уроне отображаются более наглядно.',
      ],
    },
  },
  {
    date: '2026-06-24',
    title: 'Era of Revival rollout',
    highlights: [
      'Some servers now feature the Era of Revival event and related content. More servers will unlock the event subsequently.',
      'Thief Hunt event rules adjusted—Thief Leader Level Cap now scales with server age',
      'Caravan Resource Plunder rewards enhanced',
      'Expedition Shop: reduced 10,000 Raven Fruit exchanges and added 100,000 Raven Fruit exchange option.',
    ],
    ru: {
      title: 'Запуск «Эры возрождения»',
      highlights: [
        'На части серверов запущено событие «Эра возрождения» и соответствующий контент (на остальных серверах откроется позже).',
        'Скорректированы правила Охоты на воров: максимальный уровень главаря воров теперь масштабируется с возрастом сервера.',
        'Увеличены награды за разграбление ресурсов каравана.',
        'Магазин экспедиции: убран обмен на 10 000 плодов Ворона и добавлен вариант на 100 000 плодов.',
      ],
    },
  },
  {
    date: '2026-06-16',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Fixed various known bugs'],
    ru: {
      title: 'Плановые техработы и исправления',
      highlights: ['Исправлены различные известные ошибки.'],
    },
  },
  {
    date: '2026-06-11',
    title: 'Alliance League update',
    highlights: [
      'League Phase added to Alliance Duel',
      'When each League Period starts, Kingdoms that have come online for more than 7 weeks may participate.',
      'Only the top 16 Alliances within a Kingdom by ranking can participate in the League',
      'Added three new looks and stats for Raven at Lv.150, Lv.200, and Lv.250.',
    ],
    ru: {
      title: 'Обновление Лиги Альянсов',
      highlights: [
        'В «Дуэль альянсов» добавлена фаза Лиги.',
        'В начале периода Лиги участвуют Королевства старше 7 недель с момента запуска сервера.',
        'В Лиге могут участвовать только топ-16 альянсов королевства по рейтингу.',
        'Добавлены три новых облика и характеристики Ворона на 150, 200 и 250 уровнях.',
      ],
    },
  },
  {
    date: '2026-05-29',
    title: 'Crystal Cluster Valley launch',
    highlights: [
      'Enhanced world sandbox rendering for multiple squads on-screen, improving performance and visual smoothness in multiplayer scenarios.',
      'Improved item chest opening process for Supply Chest, Raven Gear Chest, and Epigraph Chest, reducing response lag and delay.',
      'Upgraded server infrastructure for better overall performance.',
      'Added 2:00 time slot for Crystal Cluster Valley, providing greater scheduling flexibility for event participation.',
    ],
    ru: {
      title: 'Запуск «Долины кристальных скоплений»',
      highlights: [
        'Улучшен рендеринг карты при одновременном отображении нескольких отрядов (повышена плавность в массовых битвах).',
        'Ускорено открытие сундуков припасов, сундуков снаряжения Ворона и сундуков эпиграфов.',
        'Модернизирована серверная инфраструктура для снижения задержек.',
        'Добавлен временной слот 02:00 для участия в «Долине кристальных скоплений».',
      ],
    },
  },
  {
    date: '2026-05-20',
    title: 'Canyon Conquest launch',
    highlights: [
      'New Alliance Event: Canyon Conquest',
      'World map now displays the Kingdom where other players\' cities locate',
      'UR Epigraph effect adjusted — "Guard of Nature" now: Shield effect activates when battle starts, damage reduction effect activates after shield breaks',
      'Optimized Kingdom War Event, resolved lag issues',
    ],
    ru: {
      title: 'Запуск «Захвата каньона»',
      highlights: [
        'Новое событие альянса: «Захват каньона».',
        'На карте мира теперь отображается Королевство, к которому принадлежат города других игроков.',
        'Скорректирован эффект UR-эпиграфа «Страж природы»: щит активируется в начале боя, а снижение урона — после пробития щита.',
        'Оптимизировано событие «Война королевств», устранены просадки кадров.',
      ],
    },
  },
  {
    date: '2026-05-13',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Added new Emoji options',
      'King\'s Reward now displays a countdown timer until reward distribution ends',
      'Arena improvements:',
      'Matchmaking rules refined',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Добавлены новые эмодзи.',
        'В «Королевской награде» добавлен таймер обратного отсчета до завершения выдачи наград.',
        'Улучшения Арены: уточнены правила подбора противников.',
      ],
    },
  },
  {
    date: '2026-05-07',
    title: 'Crystal Cluster Valley launch',
    highlights: [
      'Frontier Pact',
      'Hero Gear System Optimization',
      'Emojis',
      'Crystal Cluster Valley',
    ],
    ru: {
      title: 'Запуск «Долины кристальных скоплений»',
      highlights: [
        'Введен «Пакт рубежа».',
        'Оптимизирована система снаряжения героев.',
        'Добавлены новые эмодзи.',
        'Старт режима «Долина кристальных скоплений».',
      ],
    },
  },
  {
    date: '2026-04-15',
    title: 'Raven Epigraphs update',
    highlights: [
      'Added Epigraph for Raven, further enhancing Raven\'s power.',
      'Fixed an issue in Elixir Scramble where Heal Speedup could not be used in certain cases.',
      'Fixed several known bugs.',
    ],
    ru: {
      title: 'Обновление Эпиграфов Ворона',
      highlights: [
        'Добавлены Эпиграфы для Ворона, значительно увеличивающие его боевую мощь.',
        'Исправлена ошибка в «Гонке за эликсиром», из-за которой ускорения лечения не применялись в определенных случаях.',
        'Исправлено несколько известных багов.',
      ],
    },
  },
  {
    date: '2026-04-09',
    title: 'Crystal Cluster Valley launch',
    highlights: [
      'Added Crystal Cluster Valley, which will unlock based on server age.',
      'Fixed an issue where Covert Operation quests could disappear under certain conditions.',
      'Fixed several known issues.',
    ],
    ru: {
      title: 'Запуск «Долины кристальных скоплений»',
      highlights: [
        'Добавлена «Долина кристальных скоплений», открывающаяся в зависимости от возраста сервера.',
        'Исправлена ошибка, из-за которой задания Спецопераций могли исчезать.',
        'Исправлен ряд известных проблем.',
      ],
    },
  },
  {
    date: '2026-04-01',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Added Easter events.',
      'Fixed several known issues.',
    ],
    ru: {
      title: 'Пасхальные события и оптимизация',
      highlights: [
        'Добавлены праздничные пасхальные события.',
        'Исправлены известные проблемы.',
      ],
    },
  },
  {
    date: '2026-03-26',
    title: 'Kingdom War launch',
    highlights: [
      'Kingdom War event, where doctors must complete Quests to earn Points and help their Kingdom achieve victory!',
      'Detailed Event rules can be found on Discord or the feature page.',
      'Optimized cross-server Caravan feature, the involved servers for the event will be displayed.',
      'New Curio Elixir obtainable via Expedition Chest (UR).',
    ],
    ru: {
      title: 'Запуск «Войны королевств»',
      highlights: [
        'Запуск события «Война королевств»: выполняйте задания, зарабатывайте очки и ведите свое Королевство к победе!',
        'Подробные правила события опубликованы в Discord и на странице режима.',
        'Оптимизирован межсерверный караван: теперь отображаются все задействованные серверы.',
        'В экспедиционных сундуках (UR) доступен новый реликт «Эликсир».',
      ],
    },
  },
  {
    date: '2026-03-18',
    title: 'Thief Hunt & Alliance optimizations',
    highlights: [
      'Optimized Caravan technologies to make them smoother.',
      'Performed a balance pass for Thief Hunt, Cheese Trap, and Wandering Blight.',
      'Improved Hero Ash\'s skill design.',
      'Optimized overall server performance.',
    ],
    ru: {
      title: 'Охота на воров и оптимизация альянса',
      highlights: [
        'Оптимизированы технологии Каравана для более плавного развития.',
        'Проведен ребаланс событий «Охота на воров», «Ловушка для сыра» и «Блуждающая скверна».',
        'Улучшен дизайн навыков героя Эш (Ash).',
        'Повышена общая производительность серверов.',
      ],
    },
  },
  {
    date: '2026-03-11',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Content in alliance announcements can now be copied.',
      'Optimized Raven upgrade operation. You can press and hold the "Feed" and "Upgrade" buttons to turn on automation.',
      'You can now tap on quoted chat to jump to the original text.',
      'Optimized Covert Operation report sorting, placing the latest records at the top.',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Текст в объявлениях альянса теперь можно копировать в буфер обмена.',
        'Оптимизировано улучшение Ворона: зажмите кнопки «Кормить» или «Улучшить» для автопрокачки.',
        'Нажатие на цитату в чате теперь переносит к исходному сообщению.',
        'Отчеты спецопераций отсортированы так, чтобы новые записи были вверху списка.',
      ],
    },
  },
  {
    date: '2026-03-04',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'New Raven special effect gear:',
      'Optimized city building layout:',
      'Optimized Research UI to improve experience (does not affect your current research progress or stats).',
      'Optimized Monthly Pass effects:',
    ],
    ru: {
      title: 'Плановые техработы и снаряжение Ворона',
      highlights: [
        'Новые элементы снаряжения со спецэффектами для Ворона.',
        'Оптимизирована сетка планировки построек в городе.',
        'Улучшен интерфейс Института (не влияет на текущий прогресс и параметры технологий).',
        'Оптимизированы эффекты Месячной карты.',
      ],
    },
  },
  {
    date: '2026-02-25',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Hero balance adjustments to better align performance with Might.',
      'Fixed several known bugs.',
    ],
    ru: {
      title: 'Баланс героев и оптимизация',
      highlights: [
        'Ребаланс характеристик героев для лучшего соответствия показателю Мощи (Might).',
        'Исправлено несколько известных ошибок.',
      ],
    },
  },
  {
    date: '2026-01-28',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Watchtower feature fix: resolved the issue of deploying heroes of non-corresponding faction;',
      'Cheese Trap Event optimization: two different options for starting time;',
      'Improved matching rules for various events;',
      'Enhanced city battle experience;',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Исправление Дозорной башни: устранена проблема назначения героев неподходящей фракции.',
        'Оптимизация «Ловушки для сыра»: два варианта времени запуска на выбор альянса.',
        'Улучшены алгоритмы матчмейкинга для ключевых событий.',
        'Доработана механика городских штурмов.',
      ],
    },
  },
  {
    date: '2026-01-21',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Optimized the Daily Quest system',
      'Improved the World Map gathering experience',
      'Added Cross-Server Caravan Trade, unlocked based on server age.',
      'Fixed multiple bugs',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Оптимизирована система ежедневных заданий.',
        'Улучшен процесс сбора ресурсов на глобальной карте.',
        'Добавлена межсерверная торговля Каравана (открывается по возрасту сервера).',
        'Исправлено множество системных ошибок.',
      ],
    },
  },
  {
    date: '2026-01-15',
    title: 'Scheduled maintenance & optimizations',
    highlights: [
      'Optimized resources collection-related features',
      'Optimized Antitoxin production',
      'Optimized Speedup function, surplus caused by Quick Speed Up will now be returned accordingly.',
      'Improved same-server Alliance Duel experience',
    ],
    ru: {
      title: 'Плановые техработы и оптимизация',
      highlights: [
        'Оптимизированы механики сбора ресурсов.',
        'Оптимизировано производство антитоксина.',
        'Доработана функция ускорений: излишки от быстрого ускорения теперь корректно возвращаются в инвентарь.',
        'Улучшен опыт участия в «Дуэли альянсов» внутри одного сервера.',
      ],
    },
  },
];
