export interface PatchNote {
  date: string; // ISO date of the announcement
  title: string;
  highlights: string[];
}

// Auto-generated by update_data.py from the official Discord #patch-notes channel.
export const patchNotes: PatchNote[] = [
  {
    date: '2026-09-02',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Added a toggle button for Official appointment notification banner. You may see this in Settings.', 'Optimized the search field for Kingdom Commendation.', 'Optimized the privilege indicators for purchased Alliance Golden Caravan.', 'Fixed an issue where the Plunder range displayed for Caravan was incorrect under certain conditions.'],
  },
  {
    date: '2026-08-27',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Difficulties 10 and 11 will be added to Pandemic Experience starting September 2.', 'Added an option to allow or block private messages from other players.', 'Added a Sanctuary Level requirement for other players to initiate private chats.', 'Covert Ops Force will now display the range of Kingdoms available for plundering.'],
  },
  {
    date: '2026-08-20',
    title: 'Raven Epigraphs update',
    highlights: ['Raven Epigraphs can now be upgraded to 6 Stars.', 'After an Exclusive Weapon reaches 10 Stars, the Smelt feature will unlock, allowing you to further enhance its attributes.', 'Optimized the display of march routes on the map.', 'Optimized the display of purchased packs on the Blades Out event screen.'],
  },
  {
    date: '2026-07-08',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Specialty Tech unlocks when Research Lab reaches Lv.30 and Elite Troop Tech reaches 80%.', 'New Alliance Event: Undead Siege (available 2 weeks after server launch).', 'Research Lab now displays recommended Tech for combat.', 'Raven Gear interface will display research Progress for Lv.8 and above equipment.'],
  },
  {
    date: '2026-05-29',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Enhanced world sandbox rendering for multiple squads on-screen, improving performance and visual smoothness in multiplayer scenarios.', 'Improved item chest opening process for Supply Chest, Raven Gear Chest, and Epigraph Chest, reducing response lag and delay.', 'Upgraded server infrastructure for better overall performance.', 'Added 2:00 time slot for Crystal Cluster Valley, providing greater scheduling flexibility for event participation.'],
  },
  {
    date: '2026-05-07',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Frontier Pact', 'Hero Gear System Optimization', 'Emojis', 'Crystal Cluster Valley'],
  },
  {
    date: '2026-04-15',
    title: 'Raven Epigraphs update',
    highlights: ['Added Epigraph for Raven, further enhancing Raven\'s power.', 'Fixed an issue in Elixir Scramble where Heal Speedup could not be used in certain cases.', 'Fixed several known bugs.'],
  },
  {
    date: '2026-04-09',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Added Crystal Cluster Valley, which will unlock based on server age.', 'Fixed an issue where Covert Operation quests could disappear under certain conditions.', 'Fixed several known issues.'],
  },
  {
    date: '2026-04-01',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Added Easter events.', 'Fixed several known issues.'],
  },
  {
    date: '2026-03-26',
    title: 'Kingdom War launch',
    highlights: ['Kingdom War event, where doctors must complete Quests to earn Points and help their Kingdom achieve victory!', 'Detailed Event rules can be found on Discord or the feature page.', 'Optimized cross-server Caravan feature, the involved servers for the event will be displayed.', 'New Curio Elixir obtainable via Expedition Chest (UR).'],
  },
  {
    date: '2026-03-18',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Optimized Caravan technologies to make them smoother.', 'Performed a balance pass for Thief Hunt, Cheese Trap, and Wandering Blight.', 'Improved Hero Ash\'s skill design.', 'Optimized overall server performance.'],
  },
  {
    date: '2026-03-11',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Content in alliance announcements can now be copied.', 'Optimized Raven upgrade operation. You can press and hold the "Feed" and "Upgrade" buttons to turn on automation.', 'You can now tap on quoted chat to jump to the original text.', 'Optimized Covert Operation report sorting, placing the latest records at the top.'],
  },
  {
    date: '2026-03-04',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['New Raven special effect gear:', 'Optimized city building layout:', 'Optimized Research UI to improve experience (does not affect your current research progress or stats).', 'Optimized Monthly Pass effects:'],
  },
  {
    date: '2026-02-25',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Hero balance adjustments to better align performance with Might.', 'Fixed several known bugs.'],
  },
  {
    date: '2026-01-28',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Watchtower feature fix: resolved the issue of deploying heroes of non-corresponding faction;', 'Cheese Trap Event optimization: two different options for starting time;', 'Improved matching rules for various events;', 'Enhanced city battle experience;'],
  },
  {
    date: '2026-01-21',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Optimized the Daily Quest system', 'Improved the World Map gathering experience', 'Added Cross-Server Caravan Trade, unlocked based on server age.', 'Fixed multiple bugs'],
  },
  {
    date: '2026-01-15',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Optimized resources collection-related features', 'Optimized Antitoxin production', 'Optimized Speedup function, surplus caused by Quick Speed Up will now be returned accordingly.', 'Improved same-server Alliance Duel experience'],
  },
];
