export interface PatchNote {
  date: string; // ISO date of the announcement
  title: string;
  highlights: string[];
}

// Auto-generated by update_data.py from the official Discord #patch-notes channel.
export const patchNotes: PatchNote[] = [
  {
    date: '2026-09-02',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Added a toggle button for Official appointment notification banner. You may see this in Settings.', 'Optimized the search field for Kingdom Commendation.', 'Optimized the privilege indicators for purchased Alliance Golden Caravan.', 'Fixed an issue where the Plunder range displayed for Caravan was incorrect under certain conditions.'],
  },
  {
    date: '2026-08-27',
    title: 'Pandemic Experience update',
    highlights: ['Difficulties 10 and 11 will be added to Pandemic Experience starting September 2.', 'Added an option to allow or block private messages from other players.', 'Added a Sanctuary Level requirement for other players to initiate private chats.', 'Covert Ops Force will now display the range of Kingdoms available for plundering.'],
  },
  {
    date: '2026-08-20',
    title: 'Raven Epigraphs update',
    highlights: ['Raven Epigraphs can now be upgraded to 6 Stars.', 'After an Exclusive Weapon reaches 10 Stars, the Smelt feature will unlock, allowing you to further enhance its attributes.', 'Optimized the display of march routes on the map.', 'Optimized the display of purchased packs on the Blades Out event screen.'],
  },
  {
    date: '2026-08-13',
    title: 'Era of Revival rollout',
    highlights: ['Era Shop now features [Castle of Revival] Skin.', 'Expedition League event duration adjusted: 56 days → 55 days.', 'Era Settlement Reward configuration optimized: [Mythic Era Commendation] chest random reward distribution refined.', 'Fixed unnecessary bubble display above alliance buildings during garrison.'],
  },
  {
    date: '2026-08-05',
    title: 'Alliance League update',
    highlights: ['Optimized icon display in the top-right corner of the main interface.', 'Optimized Relocation: allowing relocation onto Covert Operation Quests, and displaced quests will respawn.', 'Optimized Alliance Trade Caravan with added filtering options during member selection and improved VIP Passenger Wagon Reward selection interaction.', 'Optimized Alliance League Ranking interface to display the corresponding Kingdom for each Alliance; tap the Flag to view Alliance details.'],
  },
  {
    date: '2026-07-30',
    title: 'Thief Hunt & Alliance optimizations',
    highlights: ['Alliance Battle Log: View attack records from Alliance members.', 'Falcon Tower One-Tap Reward Claim unlocks at Lv.8.', 'Event Schedule: Major Events requiring reservation or scheduled activation (Hunt Battle, Cheese Trap, etc.) are now displayed in a unified Event Schedule.', 'Raven interface now features separate buttons for Skin and Upgrade Preview.'],
  },
  {
    date: '2026-07-08',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Specialty Tech unlocks when Research Lab reaches Lv.30 and Elite Troop Tech reaches 80%.', 'New Alliance Event: Undead Siege (available 2 weeks after server launch).', 'Research Lab now displays recommended Tech for combat.', 'Raven Gear interface will display research Progress for Lv.8 and above equipment.'],
  },
  {
    date: '2026-07-01',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['World Map: Sanctuary shields and Burn status are shown when zoom out.', 'Hero Name: Brian will be renamed to Ulfrid.', 'Cursed Land: Placement of new Cheese Traps will no longer be permitted in Cursed Land after this update.', 'Demon King Blight Achievement interface: Damage data will display more clearly after this update.'],
  },
  {
    date: '2026-06-24',
    title: 'Era of Revival rollout',
    highlights: ['Some servers now feature the Era of Revival event and related content. More servers will unlock the event subsequently.', 'Thief Hunt event rules adjusted—Thief Leader Level Cap now scales with server age', 'Caravan Resource Plunder rewards enhanced', 'Expedition Shop: reduced 10,000 Raven Fruit exchanges and added 100,000 Raven Fruit exchange option.'],
  },
  {
    date: '2026-06-16',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Fixed various known bugs'],
  },
  {
    date: '2026-06-11',
    title: 'Alliance League update',
    highlights: ['League Phase added to Alliance Duel', 'When each League Period starts, Kingdoms that have come online for more than 7 weeks may participate.', 'Only the top 16 Alliances within a Kingdom by ranking can participate in the League', 'Added three new looks and stats for Raven at Lv.150, Lv.200, and Lv.250.'],
  },
  {
    date: '2026-05-29',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Enhanced world sandbox rendering for multiple squads on-screen, improving performance and visual smoothness in multiplayer scenarios.', 'Improved item chest opening process for Supply Chest, Raven Gear Chest, and Epigraph Chest, reducing response lag and delay.', 'Upgraded server infrastructure for better overall performance.', 'Added 2:00 time slot for Crystal Cluster Valley, providing greater scheduling flexibility for event participation.'],
  },
  {
    date: '2026-05-20',
    title: 'Canyon Conquest launch',
    highlights: ['New Alliance Event: Canyon Conquest', 'World map now displays the Kingdom where other players\' cities locate', 'UR Epigraph effect adjusted — "Guard of Nature" now: Shield effect activates when battle starts, damage reduction effect activates after shield breaks', 'Optimized Kingdom War Event, resolved lag issues'],
  },
  {
    date: '2026-05-13',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Added new Emoji options', 'King\'s Reward now displays a countdown timer until reward distribution ends', 'Arena improvements:', 'Matchmaking rules refined'],
  },
  {
    date: '2026-05-07',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Frontier Pact', 'Hero Gear System Optimization', 'Emojis', 'Crystal Cluster Valley'],
  },
  {
    date: '2026-04-15',
    title: 'Raven Epigraphs update',
    highlights: ['Added Epigraph for Raven, further enhancing Raven\'s power.', 'Fixed an issue in Elixir Scramble where Heal Speedup could not be used in certain cases.', 'Fixed several known bugs.'],
  },
  {
    date: '2026-04-09',
    title: 'Crystal Cluster Valley launch',
    highlights: ['Added Crystal Cluster Valley, which will unlock based on server age.', 'Fixed an issue where Covert Operation quests could disappear under certain conditions.', 'Fixed several known issues.'],
  },
  {
    date: '2026-04-01',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Added Easter events.', 'Fixed several known issues.'],
  },
  {
    date: '2026-03-26',
    title: 'Kingdom War launch',
    highlights: ['Kingdom War event, where doctors must complete Quests to earn Points and help their Kingdom achieve victory!', 'Detailed Event rules can be found on Discord or the feature page.', 'Optimized cross-server Caravan feature, the involved servers for the event will be displayed.', 'New Curio Elixir obtainable via Expedition Chest (UR).'],
  },
  {
    date: '2026-03-18',
    title: 'Thief Hunt & Alliance optimizations',
    highlights: ['Optimized Caravan technologies to make them smoother.', 'Performed a balance pass for Thief Hunt, Cheese Trap, and Wandering Blight.', 'Improved Hero Ash\'s skill design.', 'Optimized overall server performance.'],
  },
  {
    date: '2026-03-11',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Content in alliance announcements can now be copied.', 'Optimized Raven upgrade operation. You can press and hold the "Feed" and "Upgrade" buttons to turn on automation.', 'You can now tap on quoted chat to jump to the original text.', 'Optimized Covert Operation report sorting, placing the latest records at the top.'],
  },
  {
    date: '2026-03-04',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['New Raven special effect gear:', 'Optimized city building layout:', 'Optimized Research UI to improve experience (does not affect your current research progress or stats).', 'Optimized Monthly Pass effects:'],
  },
  {
    date: '2026-02-25',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Hero balance adjustments to better align performance with Might.', 'Fixed several known bugs.'],
  },
  {
    date: '2026-01-28',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Watchtower feature fix: resolved the issue of deploying heroes of non-corresponding faction;', 'Cheese Trap Event optimization: two different options for starting time;', 'Improved matching rules for various events;', 'Enhanced city battle experience;'],
  },
  {
    date: '2026-01-21',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Optimized the Daily Quest system', 'Improved the World Map gathering experience', 'Added Cross-Server Caravan Trade, unlocked based on server age.', 'Fixed multiple bugs'],
  },
  {
    date: '2026-01-15',
    title: 'Scheduled maintenance & optimizations',
    highlights: ['Optimized resources collection-related features', 'Optimized Antitoxin production', 'Optimized Speedup function, surplus caused by Quick Speed Up will now be returned accordingly.', 'Improved same-server Alliance Duel experience'],
  },
];
