"""Regenerate site data files from freshly scraped Discord channels.

Run by GitHub Actions (or manually) AFTER parse_channel.py has refreshed
the JSON files in data/. Reads data/giftcode.json and data/patch-notes.json
and rewrites:
  site/src/data/giftcodes.ts
  site/src/data/patchnotes.ts
"""

import json
import re
from datetime import date, timedelta

ROOT = "D:/PythonProjects/LA_site"
DATA = f"{ROOT}/data"
SITE_DATA = f"{ROOT}/site/src/data"

TODAY = date.today()
ACTIVE_WINDOW = timedelta(days=45)  # codes newer than this are considered active


def load(fname):
    with open(f"{DATA}/{fname}", encoding="utf-8") as f:
        return json.load(f)


def extract_codes():
    gift = load("giftcode.json")
    codes = []
    code_re = re.compile(r"\b(LA[A-Z0-9]{4,12}|26[A-Z]{4,8})\b")
    note_re = re.compile(r"\*\*(.+?)\*\*")
    for m in gift["messages"]:
        c = m.get("content", "")
        for match in code_re.finditer(c):
            code = match.group(1)
            # skip Discord channel links
            if "discord.com" in c and len(code) > 10:
                pass
            note_m = note_re.search(c)
            note = (note_m.group(1) if note_m else "").strip()
            if note.lower().startswith("discord exclusive"):
                note = "Discord exclusive"
            try:
                d = m["created_at"][:10]
            except Exception:
                d = ""
            codes.append({"code": code, "date": d, "note": note or None})
    # dedupe by code, keep newest
    seen = {}
    for c in sorted(codes, key=lambda x: x["date"]):
        seen[c["code"]] = c
    out = []
    for c in seen.values():
        try:
            is_active = date.fromisoformat(c["date"]) >= TODAY - ACTIVE_WINDOW
        except Exception:
            is_active = False
        out.append({**c, "active": is_active})
    out.sort(key=lambda x: x["date"], reverse=True)
    return out


def extract_patches():
    pn = load("patch-notes.json")
    out = []
    title_re = re.compile(r"(?:^|\n)#+\s*(?:Server Maintenance(?: Notice)?|Update Notes)\s*\n*", re.I)
    for m in pn["messages"]:
        c = m.get("content", "")
        if not c.strip() or "maintenance" not in c.lower():
            continue
        d = m["created_at"][:10]
        # extract highlights: numbered lines or "New..." sections
        highlights = []
        for line in c.splitlines():
            line = line.strip()
            if re.match(r"^\d+\.\s", line) and 5 < len(line) < 160 and "UTC" not in line:
                highlights.append(re.sub(r"^[\d]+\. ", "", line))
            elif re.match(r"^\d+\.\s", line) and "UTC" in line:
                continue
        if not highlights:
            continue
        highlights = highlights[:4]
        # derive a short title from first strong signal
        text = " ".join(highlights).lower()
        if "undead siege" in text and "launch" not in text:
            title = "Undead Siege & updates"
        elif "era of revival" in text:
            title = "Era of Revival rollout"
        elif "canyon conquest" in text:
            title = "Canyon Conquest launch"
        elif "crystal cluster" in text:
            title = "Crystal Cluster Valley launch"
        elif "epigraph" in text:
            title = "Raven Epigraphs update"
        elif "kingdom war" in text:
            title = "Kingdom War launch"
        elif "hunt battle" in text:
            title = "Hunt Battle launch"
        elif "gear" in text and "promotion" in text:
            title = "Gear Promotion system"
        else:
            title = "Scheduled maintenance & optimizations"
        out.append({"date": d, "title": title, "highlights": highlights})
    # dedupe by date, newest first
    seen = {}
    for p in out:
        seen[p["date"]] = p
    return sorted(seen.values(), key=lambda x: x["date"], reverse=True)


def write_ts(codes, patches):
    ts_codes = ",\n".join(
        "  {{ code: '{code}', date: '{d}'{note}, active: {a} }}".format(
            code=c["code"], d=c["date"], note=f", note: '{c['note']}'" if c.get("note") else "", a="true" if c["active"] else "false"
        )
        for c in codes
    )
    ts_header = """export interface GiftCode {
  code: string;
  date: string; // ISO
  note?: string;
  active?: boolean;
}

// Auto-generated by update_data.py from the official Discord #giftcode channel.
// Newest codes first; active = published within the last 45 days.
export const giftCodes: GiftCode[] = [
"""
    with open(f"{SITE_DATA}/giftcodes.ts", "w", encoding="utf-8") as f:
        f.write(ts_header + ts_codes + ",\n];\n\n")
        f.write("export const REDEEM_URL = 'https://gevents.globallap.com/gamecode/index.html?gameId=440';\n")

    ts_patches = ",\n".join(
        "  {{\n    date: '{d}',\n    title: '{t}',\n    highlights: [{hl}],\n  }}".format(
            d=p["date"],
            t=p["title"],
            hl=", ".join("'" + hl.replace("'", "\\'") + "'" for hl in p["highlights"]),
        )
        for p in patches
    )
    ts_p_header = """export interface PatchNote {
  date: string; // ISO date of the announcement
  title: string;
  highlights: string[];
}

// Auto-generated by update_data.py from the official Discord #patch-notes channel.
export const patchNotes: PatchNote[] = [
"""
    with open(f"{SITE_DATA}/patchnotes.ts", "w", encoding="utf-8") as f:
        f.write(ts_p_header + ts_patches + ",\n];\n")


if __name__ == "__main__":
    codes = extract_codes()
    patches = extract_patches()
    write_ts(codes, patches)
    print(f"giftcodes.ts: {len(codes)} codes ({sum(1 for c in codes if c['active'])} active)")
    print(f"patchnotes.ts: {len(patches)} patch notes")