"""Regenerate site data files from freshly scraped Discord channels.

Run by GitHub Actions (or manually) AFTER parse_channel.py has refreshed
the JSON files in data/. Reads data/patch-notes.json
and rewrites:
  site/src/data/patchnotes.ts
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = f"{ROOT}/data"
SITE_DATA = f"{ROOT}/site/src/data"



def load(fname):
    with open(f"{DATA}/{fname}", encoding="utf-8") as f:
        return json.load(f)


def extract_patches():
    pn = load("patch-notes.json")
    out = []
    for m in pn["messages"]:
        c = m.get("content", "")
        if not c.strip():
            continue
        c_lower = c.lower()
        if "maintenance" not in c_lower and "update notes" not in c_lower and "new content" not in c_lower:
            continue
        d = m["created_at"][:10]
        # extract highlights: numbered lines or bullet lines
        highlights = []
        for line in c.splitlines():
            line = line.strip()
            if re.match(r"^\d+\.\s", line) and 5 < len(line) < 160 and "UTC" not in line:
                highlights.append(re.sub(r"^[\d]+\. ", "", line))
            elif re.match(r"^-\s", line) and 5 < len(line) < 160 and "UTC" not in line:
                highlights.append(re.sub(r"^-\s*", "", line))
            elif re.match(r"^[a-z]\.\s", line) and 5 < len(line) < 160:
                highlights.append(re.sub(r"^[a-z]\.\s*", "", line))
        if not highlights:
            continue
        highlights = highlights[:4]
        # derive a short title from first strong signal
        text = " ".join(highlights).lower()
        if "undead siege" in text and "launch" not in text:
            title = "Undead Siege & updates"
        elif "era of revival" in text or "castle of revival" in text:
            title = "Era of Revival rollout"
        elif "canyon conquest" in text:
            title = "Canyon Conquest launch"
        elif "crystal cluster" in text:
            title = "Crystal Cluster Valley launch"
        elif "epigraph" in text:
            title = "Raven Epigraphs update"
        elif "kingdom war" in text:
            title = "Kingdom War launch"
        elif "hunt battle" in text or "thief hunt" in text or "bandit hunt" in text:
            title = "Thief Hunt & Alliance optimizations"
        elif "league phase" in text or "alliance league" in text:
            title = "Alliance League update"
        elif "smelt" in text:
            title = "Exclusive Weapon Smelt & Raid Buffs"
        elif "pandemic" in text:
            title = "Pandemic Experience update"
        elif "gear" in text and "promotion" in text:
            title = "Gear Promotion system"
        else:
            title = "Scheduled maintenance & optimizations"
        out.append({"date": d, "title": title, "highlights": highlights})
    # dedupe by date, newest first
    seen = {}
    for p in out:
        seen[p["date"]] = p
    return sorted(seen.values(), key=lambda x: x["date"], reverse=True)


def write_ts(patches):
    ts_patches = ",\n".join(
        "  {{\n    date: '{d}',\n    title: '{t}',\n    highlights: [{hl}],\n  }}".format(
            d=p["date"],
            t=p["title"],
            hl=", ".join("'" + hl.replace("'", "\\'") + "'" for hl in p["highlights"]),
        )
        for p in patches
    )
    ts_p_header = """export interface PatchNote {
  date: string; // ISO date of the announcement
  title: string;
  highlights: string[];
}

// Auto-generated by update_data.py from the official Discord #patch-notes channel.
export const patchNotes: PatchNote[] = [
"""
    with open(f"{SITE_DATA}/patchnotes.ts", "w", encoding="utf-8") as f:
        f.write(ts_p_header + ts_patches + ",\n];\n")


if __name__ == "__main__":
    patches = extract_patches()
    write_ts(patches)
    print(f"patchnotes.ts: {len(patches)} patch notes")